// Canonical demo accounts aligned with database seeds & quick preset profiles
export const DEMO_ACCOUNTS = {
  'admin@zuna.com': {
    id: 'usr-superadmin-zuna',
    name: 'Super Administrator',
    fullName: 'Super Administrator',
    email: 'admin@zuna.com',
    phone: '+1 (555) 019-9922',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=300',
    userType: 'SUPERADMIN',
    role: 'SUPERADMIN',
    roleTitle: 'Superadministrator',
    isSuperadmin: true,
    isAdmin: true,
    tenantId: null,
    clinicName: 'Global Platform Operations',
    tenant: null,
    roles: ['SUPERADMIN'],
    permissions: ['*'],
  },
  'superadmin@clinic.io': {
    id: 'usr-superadmin',
    name: 'Alexander Sterling',
    fullName: 'Alexander Sterling',
    email: 'superadmin@clinic.io',
    phone: '+1 (555) 019-2831',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=300',
    userType: 'SUPERADMIN',
    role: 'SUPERADMIN',
    roleTitle: 'Superadministrator',
    isSuperadmin: true,
    isAdmin: true,
    tenantId: null,
    clinicName: 'Global Platform Operations',
    tenant: null,
    roles: ['SUPERADMIN'],
    permissions: ['*'],
  },
  'superadmin@clinic.io': {
    id: 'usr-superadmin',
    name: 'Alexander Sterling',
    fullName: 'Alexander Sterling',
    email: 'superadmin@clinic.io',
    phone: '+1 (555) 019-2831',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=300',
    userType: 'SUPERADMIN',
    role: 'SUPERADMIN',
    roleTitle: 'Superadministrator',
    isSuperadmin: true,
    isAdmin: true,
    tenantId: null,
    clinicName: 'Global Platform Operations',
    tenant: null,
    roles: ['SUPERADMIN'],
    permissions: ['*'],
  },
  'admin@aurahealth.org': {
    id: 'usr-admin-1',
    name: 'Dr. Evelyn Vance',
    fullName: 'Dr. Evelyn Vance',
    email: 'admin@aurahealth.org',
    phone: '+1 (555) 234-5678',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=300',
    userType: 'ADMIN',
    role: 'ADMIN',
    roleTitle: 'Clinic Administrator',
    isSuperadmin: false,
    isAdmin: true,
    tenantId: 'clinic-1',
    clinicName: 'Aura Health Memorial',
    tenant: { id: 'clinic-1', name: 'Aura Health Memorial', subdomain: 'aura-health' },
    roles: ['ADMIN', 'Clinical Administrator'],
    permissions: [
      'patients.view', 'patients.create', 'patients.edit', 'patients.delete', 'patients.export',
      'appointments.view', 'appointments.create', 'appointments.edit', 'appointments.delete', 'appointments.export',
      'prescriptions.view', 'prescriptions.create', 'prescriptions.edit', 'prescriptions.delete', 'prescriptions.export',
      'billing.view', 'billing.create', 'billing.edit', 'billing.delete', 'billing.export',
      'inventory.view', 'inventory.create', 'inventory.edit', 'inventory.delete', 'inventory.export',
      'staff.view', 'staff.create', 'staff.edit', 'staff.delete', 'staff.export',
      'roles.view', 'roles.create', 'roles.edit', 'roles.delete',
      'reports.view', 'reports.export',
      'clinical_config.view', 'clinical_config.edit',
      'settings.view', 'settings.edit',
      'patients.*', 'appointments.*', 'prescriptions.*', 'billing.*', 'inventory.*', 'staff.*', 'roles.*', 'reports.*', 'clinical_config.*'
    ],
  },
  'admin@clinic.io': {
    id: 'usr-admin-1',
    name: 'Dr. Evelyn Vance',
    fullName: 'Dr. Evelyn Vance',
    email: 'admin@clinic.io',
    phone: '+1 (555) 234-5678',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=300',
    userType: 'ADMIN',
    role: 'ADMIN',
    roleTitle: 'Clinic Administrator',
    isSuperadmin: false,
    isAdmin: true,
    tenantId: 'clinic-1',
    clinicName: 'Aura Health Memorial',
    tenant: { id: 'clinic-1', name: 'Aura Health Memorial', subdomain: 'aura-health' },
    roles: ['ADMIN', 'Clinical Administrator'],
    permissions: ['patients.*', 'appointments.*', 'prescriptions.*', 'billing.*', 'inventory.*', 'staff.*', 'roles.*', 'reports.*', 'clinical_config.*', 'settings.*'],
  },
  'doctor@clinic.io': {
    id: 'usr-doctor-1',
    name: 'Dr. Sarah Al-Mansoor',
    fullName: 'Dr. Sarah Al-Mansoor',
    email: 'doctor@clinic.io',
    phone: '+1 (555) 123-4567',
    avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=300',
    userType: 'STAFF',
    role: 'DOCTOR',
    roleTitle: 'Senior Attending Physician',
    isSuperadmin: false,
    isAdmin: false,
    tenantId: 'clinic-1',
    clinicName: 'Aura Health Memorial',
    tenant: { id: 'clinic-1', name: 'Aura Health Memorial', subdomain: 'aura-health' },
    roles: ['Senior Attending Physician'],
    permissions: [
      'patients.view', 'patients.edit', 'patients.export',
      'appointments.view', 'appointments.create', 'appointments.edit',
      'prescriptions.view', 'prescriptions.create', 'prescriptions.edit', 'prescriptions.export',
      'inventory.view',
      'reports.view',
    ],
  },
  'doctor@clinic.io': {
    id: 'usr-doctor-1',
    name: 'Dr. Sarah Al-Mansoor',
    fullName: 'Dr. Sarah Al-Mansoor',
    email: 'doctor@clinic.io',
    phone: '+1 (555) 123-4567',
    avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=300',
    userType: 'STAFF',
    role: 'DOCTOR',
    roleTitle: 'Senior Attending Physician',
    isSuperadmin: false,
    isAdmin: false,
    tenantId: 'clinic-1',
    clinicName: 'Aura Health Memorial',
    tenant: { id: 'clinic-1', name: 'Aura Health Memorial', subdomain: 'aura-health' },
    roles: ['Senior Attending Physician'],
    permissions: [
      'patients.view', 'patients.edit', 'patients.export',
      'appointments.view', 'appointments.create', 'appointments.edit',
      'prescriptions.view', 'prescriptions.create', 'prescriptions.edit', 'prescriptions.export',
      'inventory.view',
      'reports.view',
    ],
  },
  'reception@clinic.io': {
    id: 'usr-reception-1',
    name: 'Elena Rostova',
    fullName: 'Elena Rostova',
    email: 'reception@clinic.io',
    phone: '+1 (555) 345-6789',
    avatar: 'https://images.unsplash.com/photo-1594824813572-c24458514131?auto=format&fit=crop&q=80&w=300',
    userType: 'STAFF',
    role: 'RECEPTIONIST',
    roleTitle: 'Front Desk & Receptionist',
    isSuperadmin: false,
    isAdmin: false,
    tenantId: 'clinic-1',
    clinicName: 'Aura Health Memorial',
    tenant: { id: 'clinic-1', name: 'Aura Health Memorial', subdomain: 'aura-health' },
    roles: ['Front Desk & Receptionist'],
    permissions: [
      'patients.view', 'patients.create', 'patients.edit',
      'appointments.view', 'appointments.create', 'appointments.edit',
      'billing.view', 'billing.create',
      'inventory.view',
    ],
  },
  'reception@clinic.io': {
    id: 'usr-reception-1',
    name: 'Elena Rostova',
    fullName: 'Elena Rostova',
    email: 'reception@clinic.io',
    phone: '+1 (555) 345-6789',
    avatar: 'https://images.unsplash.com/photo-1594824813572-c24458514131?auto=format&fit=crop&q=80&w=300',
    userType: 'STAFF',
    role: 'RECEPTIONIST',
    roleTitle: 'Front Desk & Receptionist',
    isSuperadmin: false,
    isAdmin: false,
    tenantId: 'clinic-1',
    clinicName: 'Aura Health Memorial',
    tenant: { id: 'clinic-1', name: 'Aura Health Memorial', subdomain: 'aura-health' },
    roles: ['Front Desk & Receptionist'],
    permissions: [
      'patients.view', 'patients.create', 'patients.edit',
      'appointments.view', 'appointments.create', 'appointments.edit',
      'billing.view', 'billing.create',
      'inventory.view',
      'prescriptions.view',
    ],
  },
  'nurse@clinic.io': {
    id: 'usr-nurse-1',
    name: 'James C. Rodriguez',
    fullName: 'James C. Rodriguez',
    email: 'nurse@clinic.io',
    phone: '+1 (555) 456-7890',
    avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=300',
    userType: 'STAFF',
    role: 'NURSE',
    roleTitle: 'Registered Clinical Nurse',
    isSuperadmin: false,
    isAdmin: false,
    tenantId: 'clinic-1',
    clinicName: 'Aura Health Memorial',
    tenant: { id: 'clinic-1', name: 'Aura Health Memorial', subdomain: 'aura-health' },
    roles: ['Registered Clinical Nurse'],
    permissions: [
      'patients.view', 'patients.create', 'patients.edit',
      'appointments.view',
      'prescriptions.view',
      'inventory.view',
    ],
  },
  'biller@clinic.io': {
    id: 'usr-biller-1',
    name: 'Amara Chen',
    fullName: 'Amara Chen',
    email: 'biller@clinic.io',
    phone: '+1 (555) 567-8901',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=300',
    userType: 'STAFF',
    role: 'BILLER',
    roleTitle: 'Billing & Insurance Specialist',
    isSuperadmin: false,
    isAdmin: false,
    tenantId: 'clinic-1',
    clinicName: 'Aura Health Memorial',
    tenant: { id: 'clinic-1', name: 'Aura Health Memorial', subdomain: 'aura-health' },
    roles: ['Billing & Insurance Specialist'],
    permissions: [
      'patients.view',
      'billing.view', 'billing.create', 'billing.edit', 'billing.export',
      'reports.view', 'reports.export',
      'inventory.view',
      'prescriptions.view',
    ],
  },
  'nurse@clinic.io': {
    id: 'usr-nurse-1',
    name: 'James C. Rodriguez',
    fullName: 'James C. Rodriguez',
    email: 'nurse@clinic.io',
    phone: '+1 (555) 456-7890',
    avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=300',
    userType: 'STAFF',
    role: 'NURSE',
    roleTitle: 'Registered Clinical Nurse',
    isSuperadmin: false,
    isAdmin: false,
    tenantId: 'clinic-1',
    clinicName: 'Aura Health Memorial',
    tenant: { id: 'clinic-1', name: 'Aura Health Memorial', subdomain: 'aura-health' },
    roles: ['Registered Clinical Nurse'],
    permissions: [
      'patients.view', 'patients.create', 'patients.edit',
      'appointments.view',
      'prescriptions.view',
      'inventory.view',
    ],
  },
}

// Map simulation and alternative IDs directly
DEMO_ACCOUNTS['staff-1'] = DEMO_ACCOUNTS['doctor@clinic.io'] || DEMO_ACCOUNTS['doctor@clinic.io']
DEMO_ACCOUNTS['staff-2'] = DEMO_ACCOUNTS['reception@clinic.io']
DEMO_ACCOUNTS['staff-3'] = DEMO_ACCOUNTS['nurse@clinic.io']
DEMO_ACCOUNTS['staff-4'] = DEMO_ACCOUNTS['biller@clinic.io']
DEMO_ACCOUNTS['admin-1'] = DEMO_ACCOUNTS['admin@aurahealth.org']
DEMO_ACCOUNTS['usr-admin-1'] = DEMO_ACCOUNTS['admin@aurahealth.org']
DEMO_ACCOUNTS['usr-doctor-1'] = DEMO_ACCOUNTS['doctor@clinic.io']
DEMO_ACCOUNTS['usr-reception-1'] = DEMO_ACCOUNTS['reception@clinic.io']
DEMO_ACCOUNTS['usr-nurse-1'] = DEMO_ACCOUNTS['nurse@clinic.io']
DEMO_ACCOUNTS['usr-biller-1'] = DEMO_ACCOUNTS['biller@clinic.io']

